language: php

php:
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "5.2" ]]; then cp .travis.composer.json composer.json; else echo 'PHP 5.2 build skips composer installation'; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "5.2" ]]; then curl -s http://getcomposer.org/installer | php; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "5.2" ]]; then php composer.phar install --dev --no-interaction; fi

script:
  - mkdir -p build/logs
  - phpunit

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "5.2" ]]; then php vendor/bin/coveralls -v; else echo 'PHP 5.2 build skips php-coveralls'; fi
